-- S'Clean production schema: Supabase Auth + Postgres.
-- Apply in Supabase SQL Editor, then set the first admin role explicitly.

create table if not exists public.sclean_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  phone text,
  full_name text,
  role text not null default 'client'
    check (role in ('client', 'admin', 'staff')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sclean_services (
  id integer generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text not null default '',
  price integer not null check (price > 0),
  duration_minutes integer not null
    check (duration_minutes > 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.sclean_zones (
  id integer generated by default as identity primary key,
  name text not null unique,
  travel_fee integer not null default 0
    check (travel_fee >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.sclean_availability (
  id integer generated by default as identity primary key,
  day_of_week integer not null
    check (day_of_week between 0 and 6),
  start_time time not null,
  end_time time not null,
  break_start time,
  break_end time,
  active boolean not null default true
);

create table if not exists public.sclean_blocked_slots (
  id integer generated by default as identity primary key,
  start_at timestamptz not null,
  end_at timestamptz not null,
  reason text not null,
  created_at timestamptz not null default now(),
  check (end_at > start_at)
);

create table if not exists public.sclean_bookings (
  booking_number text primary key,
  user_id uuid references auth.users(id)
    on delete set null,
  email text,
  customer_name text not null,
  phone text not null,
  vehicle text not null,
  service_id integer not null
    references public.sclean_services(id),
  service_name text not null,
  date date not null,
  start_time time not null,
  end_time time not null,
  address text not null,
  neighborhood text not null,
  landmark text,
  total_price integer not null
    check (total_price > 0),
  status text not null default 'confirmed'
    check (
      status in (
        'pending',
        'confirmed',
        'completed',
        'cancelled',
        'in_progress',
        'no_show'
      )
    ),
  payment_status text not null default 'unpaid'
    check (
      payment_status in (
        'unpaid',
        'partial',
        'paid'
      )
    ),
  created_at timestamptz not null default now()
);

create unique index if not exists
  sclean_bookings_slot_unique
on public.sclean_bookings(date, start_time)
where status <> 'cancelled';

create index if not exists
  sclean_bookings_user_id_idx
on public.sclean_bookings(user_id);

create index if not exists
  sclean_bookings_date_idx
on public.sclean_bookings(date, start_time);

insert into public.sclean_services (
  id,
  name,
  slug,
  description,
  price,
  duration_minutes
)
values
  (
    1,
    'Lavage basique',
    'lavage-basique',
    'L’essentiel pour garder votre véhicule propre au quotidien.',
    3500,
    45
  ),
  (
    2,
    'Lavage Premium',
    'lavage-premium',
    'Un nettoyage plus complet pour une voiture propre dedans et dehors.',
    7000,
    75
  ),
  (
    3,
    'Premium Protection',
    'premium-protection',
    'Le soin complet pour nettoyer, faire briller et protéger votre véhicule.',
    10000,
    105
  )
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  description = excluded.description,
  price = excluded.price,
  duration_minutes = excluded.duration_minutes;

insert into public.sclean_zones (
  name,
  travel_fee
)
values
  ('Cocody', 0),
  ('Riviera', 0),
  ('M''Pouto', 0),
  ('Zone éloignée', 3000)
on conflict (name) do update set
  travel_fee = excluded.travel_fee;

-- Atomic server-side booking creation.
-- The advisory lock serializes bookings for a date.

create or replace function public.create_sclean_booking(
  p_booking_number text,
  p_user_id uuid,
  p_email text,
  p_customer_name text,
  p_phone text,
  p_vehicle text,
  p_service_id integer,
  p_date date,
  p_start_time time,
  p_address text,
  p_neighborhood text,
  p_landmark text default null
)
returns public.sclean_bookings
language plpgsql
security definer
set search_path = public
as $$
declare
  v_service public.sclean_services;
  v_zone_fee integer;
  v_end_time time;
  v_total integer;
  v_result public.sclean_bookings;
begin
  perform pg_advisory_xact_lock(
    hashtext('sclean-booking-' || p_date::text)
  );

  select *
  into v_service
  from public.sclean_services
  where id = p_service_id
    and active = true;

  if not found then
    raise exception 'SERVICE_UNAVAILABLE';
  end if;

  select coalesce(travel_fee, 0)
  into v_zone_fee
  from public.sclean_zones
  where name = p_neighborhood
    and active = true;

  if v_zone_fee is null then
    raise exception 'ZONE_UNAVAILABLE';
  end if;

  v_end_time :=
    p_start_time
    + make_interval(mins => v_service.duration_minutes);

  v_total := v_service.price + v_zone_fee;

  if
    p_start_time < time '08:00'
    or v_end_time > time '18:00'
    or (
      p_start_time < time '13:00'
      and v_end_time > time '12:00'
    )
  then
    raise exception 'OUTSIDE_HOURS';
  end if;

  if exists (
    select 1
    from public.sclean_bookings b
    where b.date = p_date
      and b.status <> 'cancelled'
      and b.start_time < v_end_time
      and b.end_time >
        (p_start_time - interval '30 minutes')
  ) then
    raise exception 'SLOT_UNAVAILABLE';
  end if;

  insert into public.sclean_bookings (
    booking_number,
    user_id,
    email,
    customer_name,
    phone,
    vehicle,
    service_id,
    service_name,
    date,
    start_time,
    end_time,
    address,
    neighborhood,
    landmark,
    total_price
  )
  values (
    p_booking_number,
    p_user_id,
    p_email,
    p_customer_name,
    p_phone,
    p_vehicle,
    p_service_id,
    v_service.name,
    p_date,
    p_start_time,
    v_end_time,
    p_address,
    p_neighborhood,
    p_landmark,
    v_total
  )
  returning *
  into v_result;

  return v_result;
end;
$$;

alter table public.sclean_profiles
enable row level security;

alter table public.sclean_services
enable row level security;

alter table public.sclean_zones
enable row level security;

alter table public.sclean_availability
enable row level security;

alter table public.sclean_bookings
enable row level security;

drop policy if exists "profiles_read_own"
on public.sclean_profiles;

create policy "profiles_read_own"
on public.sclean_profiles
for select
to authenticated
using (id = auth.uid());

drop policy if exists "services_public_read"
on public.sclean_services;

create policy "services_public_read"
on public.sclean_services
for select
to anon, authenticated
using (active = true);

drop policy if exists "zones_public_read"
on public.sclean_zones;

create policy "zones_public_read"
on public.sclean_zones
for select
to anon, authenticated
using (active = true);

drop policy if exists "bookings_read_own"
on public.sclean_bookings;

create policy "bookings_read_own"
on public.sclean_bookings
for select
to authenticated
using (user_id = auth.uid());

-- After the first user registers, run:
-- update public.sclean_profiles
-- set role = 'admin'
-- where email = 'admin@example.com';
